version: '3.8'

services:
  db:
    image: mariadb
    container_name: blog_mariadb
    restart: always
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:3306
    environment:
      MARIADB_HOST: ${DB_HOST}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      blog-network:
        ipv4_address: ${DB_IP_ADDRESS}

  phpmyadmin:
    image: phpmyadmin
    container_name: blog_phpmyadmin
    restart: always
    ports:
      - ${DB_PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
    links:
      - db
    depends_on:
      - db
    networks:
      blog-network:
        ipv4_address: ${DB_PHPMYADMIN_IP_ADDRESS}

  web:
    image: nginx:latest
    container_name: blog_nginx
    restart: always
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - db
    networks:
      blog-network:
        ipv4_address: ${WEB_IP_ADDRESS}

  php:
    image: blog_php
    container_name: blog_php
    build: .
    volumes:
      - ./web:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/html
    expose:
      - 9000
    ports:
      - ${PHP_PORT}:9000
    restart: always
    links:
      - db
    depends_on:
      - db
      - web
    networks:
      blog-network:
        ipv4_address: ${PHP_IP_ADDRESS}

networks:
  blog-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${BLOG_NETWORK_SUBNET}
          gateway: ${BLOG_NETWORK_GATEWAY}

volumes:
  db:
