version: '3.8'

services:
  db:
    image: mariadb
    container_name: blog_mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - db:/var/lib/mysql
    networks:
      blog-network:
        ipv4_address: 176.0.0.2

  phpmyadmin:
    image: phpmyadmin
    container_name: blog_phpmyadmin
    restart: always
    ports:
      - 8080:8080
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root
    links:
      - db
    depends_on:
      - db
    networks:
      blog-network:
        ipv4_address: 176.0.0.3

  web:
    image: nginx:latest
    container_name: blog_nginx
    restart: always
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      blog-network:
        ipv4_address: 176.0.0.4

  php:
    image: blog_php
    container_name: blog_php
    build: .
    volumes:
      - ./web:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/html
    expose:
      - 9000
    ports:
      - 9000:9000
    restart: always
    links:
      - db
    depends_on:
      - db
      - web
    networks:
      blog-network:
        ipv4_address: 176.0.0.5

networks:
  blog-network:
    driver: bridge
    ipam:
      config:
        - subnet: 176.0.0.0/24
          gateway: 176.0.0.1

volumes:
  db:
